//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drive
    {
        public int driveCode { get; set; }
        public string driverCode { get; set; }
        public string customerCode { get; set; }
        public System.TimeSpan drivingTime { get; set; }
        public System.DateTime travelDate { get; set; }
        public int fromLocation { get; set; }
        public int toLocation { get; set; }
        public string describeDrive { get; set; }
        public Nullable<bool> status { get; set; }
        public int transportation { get; set; }
        public Nullable<int> price { get; set; }
        public bool message { get; set; }
        public Nullable<double> distance { get; set; }
    }
}
