//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Happiness
    {
        public int id { get; set; }
        public string deliveryId { get; set; }
        public string customerName { get; set; }
        public System.DateTime date { get; set; }
        public int happinessLevel { get; set; }
        public string describeHappiness { get; set; }
    }
}
