//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loction()
        {
<<<<<<< HEAD
            this.Package = new HashSet<Package>();
            this.Package1 = new HashSet<Package>();
=======
            this.Drives = new HashSet<Drive>();
            this.Drives1 = new HashSet<Drive>();
            this.Packages = new HashSet<Package>();
            this.Packages1 = new HashSet<Package>();
>>>>>>> 707e59e777cf3c9a9d6fbbd95c355d6f8e4f4e01
        }
    
        public int locationId { get; set; }
        public string locationFormat { get; set; }
        public Nullable<double> locationLat { get; set; }
        public Nullable<double> locationLng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< HEAD
        public virtual ICollection<Package> Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Package1 { get; set; }
=======
        public virtual ICollection<Drive> Drives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drive> Drives1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages1 { get; set; }
>>>>>>> 707e59e777cf3c9a9d6fbbd95c355d6f8e4f4e01
    }
}
