//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loction
    {
        public int locationId { get; set; }
        public string locationFormat { get; set; }
        public Nullable<double> locationLat { get; set; }
        public Nullable<double> locationLng { get; set; }
    }
}
