//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDeliveries1Entities : DbContext
    {
        public DBDeliveries1Entities()
            : base("name=DBDeliveries1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< HEAD
        public virtual DbSet<Drive> Drive { get; set; }
        public virtual DbSet<Happiness> Happiness { get; set; }
        public virtual DbSet<Loction> Loction { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<PackageSize> PackageSize { get; set; }
        public virtual DbSet<PackageType> PackageType { get; set; }
        public virtual DbSet<Transportation> Transportation { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WaitingMessages> WaitingMessages { get; set; }
=======
        public virtual DbSet<Drive> Drives { get; set; }
        public virtual DbSet<Loction> Loctions { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PackageDescription> PackageDescriptions { get; set; }
        public virtual DbSet<PackageSize> PackageSizes { get; set; }
        public virtual DbSet<PackageType> PackageTypes { get; set; }
        public virtual DbSet<RefusesPackage> RefusesPackages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
>>>>>>> 707e59e777cf3c9a9d6fbbd95c355d6f8e4f4e01
    }
}
