//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDeliveriesEntities : DbContext
    {
        public DBDeliveriesEntities()
            : base("name=DBDeliveriesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drive> Drive { get; set; }
        public virtual DbSet<Happiness> Happiness { get; set; }
        public virtual DbSet<Loction> Loction { get; set; }
        public virtual DbSet<Package> Package { get; set; }
        public virtual DbSet<PackageSize> PackageSize { get; set; }
        public virtual DbSet<PackageType> PackageType { get; set; }
        public virtual DbSet<Transportation> Transportation { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WaitingMessages> WaitingMessages { get; set; }
    }
}
