//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int packageCode { get; set; }
        public string userCustomerCode { get; set; }
        public string userDeliveryCode { get; set; }
        public int fromLocation { get; set; }
        public int toLocation { get; set; }
        public System.DateTime fromDate { get; set; }
        public System.DateTime toDate { get; set; }
        public System.TimeSpan fromTime { get; set; }
        public System.TimeSpan toTime { get; set; }
        public bool status { get; set; }
        public int packageType { get; set; }
        public string describePackage { get; set; }
        public int packageSize { get; set; }
        public bool message { get; set; }
        public Nullable<double> distance { get; set; }
    }
}
