//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.WaitingMessages = new HashSet<WaitingMessages>();
        }
    
        public int packageCode { get; set; }
        public string userCustomerCode { get; set; }
        public string userDeliveryCode { get; set; }
        public int fromLocation { get; set; }
        public int toLocation { get; set; }
        public System.DateTime travelDate { get; set; }
        public System.TimeSpan drivingTime { get; set; }
<<<<<<< HEAD
        public Nullable<bool> status { get; set; }
=======
        public bool confirmationDelivery { get; set; }
        public int happinesslevel { get; set; }
        public string describeHappiness { get; set; }
>>>>>>> 707e59e777cf3c9a9d6fbbd95c355d6f8e4f4e01
        public int packageType { get; set; }
        public string describePackage { get; set; }
        public int packageSize { get; set; }
    
        public virtual Loction Loction { get; set; }
        public virtual Loction Loction1 { get; set; }
        public virtual PackageSize PackageSize1 { get; set; }
        public virtual PackageType PackageType1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingMessages> WaitingMessages { get; set; }
    }
}
