//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class packageDescription
    {
        public int packageDescriptionCode { get; set; }
        public string userCode { get; set; }
        public int packageType { get; set; }
        public string value { get; set; }
    
        public virtual PackageType PackageType1 { get; set; }
        public virtual User User { get; set; }
    }
}
