//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int packageCode { get; set; }
        public string userCustomerCode { get; set; }
        public string userDeliveryCode { get; set; }
        public string fromLocation { get; set; }
        public string toLocation { get; set; }
        public System.DateTime travelDate { get; set; }
        public System.TimeSpan drivingTime { get; set; }
        public string redinessForChanges { get; set; }
        public bool confirmationDelivery { get; set; }
        public Nullable<System.TimeSpan> watingTimeForConfirmation { get; set; }
        public int happinesslevel { get; set; }
        public string describeHappiness { get; set; }
        public int packageType { get; set; }
        public string describePackage { get; set; }
        public int packageSize { get; set; }
    
        public virtual PackageSize PackageSize1 { get; set; }
        public virtual PackageType PackageType1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
