//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingMessage
    {
        public int id { get; set; }
        public int packageId { get; set; }
        public int driveId { get; set; }
        public bool status { get; set; }
        public Nullable<int> totalPrice { get; set; }
    }
}
