//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
<<<<<<< HEAD:tester/DAL/WaitingMessages.cs
    public partial class WaitingMessages
=======
    public partial class PackageDescription
>>>>>>> 707e59e777cf3c9a9d6fbbd95c355d6f8e4f4e01:tester/DAL/packageDescription.cs
    {
        public int id { get; set; }
        public int packageId { get; set; }
        public int driveId { get; set; }
        public bool status { get; set; }
    
        public virtual Drive Drive { get; set; }
        public virtual Package Package { get; set; }
    }
}
